'use client'
import Head from 'next/head'

import { useState} from 'react'

import axios from 'axios';

import Link from 'next/link';



export default function Home() {

  const [nome, setNome] = useState("");
  const [numero, setNumero] = useState("")


  const handleSubmit = async(e) => {

    e.preventDefault();

    console.log("Dados Atualizados", {nome, numero})  

    axios
      .post('/api/user', {nome, numero})
      .then((response) => {
        console.log("Dados enviados")
      }).catch((err) => {
        console.log(err)
      })

      setNome("")
      setNumero("")


  }

  return (
    <>
      <Head>
        <title>Cadastrar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
        <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Nome"
          value={nome}
          onChange={(e) => setNome(e.target.value)}
        />
        <input
          type="number"
          placeholder="Contato"
          value={numero}
          onChange={(e) => setNumero(e.target.value)}
        />

        <button type="submit">Enviar</button>
      </form>
        </div>
        <button><Link href={'/home'}>Ir para home</Link></button>
      </main>
    </>
  )
}
